version: '3.4'
services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile.passenger
    ports:
      - 80:80
      - "3000:3000"
      - "443:443"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      AUTH_SERVER_ID: ${AUTH_SERVER_ID}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      HOST_NAME: ${HOST_NAME}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PASSENGER_APP_ENV: ${PASSENGER_APP_ENV}
      OAUTHTOKEN: ${OAUTHTOKEN}


  mysql:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.mysql
    command: --max_allowed_packet=32505856
    ports:
      - "3306:3306"      
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}     
      MYSQL_PASSWORD:  ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME} 
  solr:
    build:
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "8983:8983"