FROM solr:8.1-slim

RUN mkdir -p /var/solr/data/freshwriting/conf
COPY --chown=solr core.properties /var/solr/data/freshwriting/core.properties
COPY --chown=solr solr_conf/* /var/solr/data/freshwriting/conf/
